name: Statistics

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04

    name: Generate framework stats

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis-phpredis/phpredis@5.3.5, igbinary, msgpack, lzf, zstd, lz4, memcached
          ini-values: error_reporting=E_ALL
          tools: composer:v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHPUnit Coverage Creation
        run: vendor/bin/phpunit --coverage-clover ./build/logs/coverage.xml
        env:
          XDEBUG_MODE: coverage

      - name: Install Coveralls client
        run: composer global require php-coveralls/php-coveralls

      - name: Upload Coveralls Coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_ACCESS_TOKEN }}
        run: php-coveralls --coverage_clover=build/logs/coverage.xml -v